idioma: English
logging:
  formatters:
    debug_formatter:
      datefmt: '%Y-%m-%d %H:%M:%S'
      format: '[%(asctime)s][%(levelname)s][%(name)s][%(module)s|%(lineno)s]. %(message)s'
    default_formatter:
      datefmt: '%Y-%m-%d %H:%M:%S'
      format: '[%(asctime)s].%(levelname)s. %(message)s'
  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: debug_formatter
      level: DEBUG
      stream: ext://sys.stdout
    error_handler:
      class: logging.FileHandler
      filename: error.log
      formatter: debug_formatter
      level: ERROR
      mode: w
    file_handler:
      class: logging.FileHandler
      filename: output.log
      formatter: default_formatter
      level: INFO
  loggers:
    error_logger:
      handlers:
      - error_handler
      - console_handler
      level: CRITICAL
    root:
      handlers:
      - file_handler
      - console_handler
      level: INFO
  version: 1
path_ffmpeg: D:/Formacion/ffmpeg-6.1-essentials_build/bin
path_sw: null
path_sw_out: null
